import type {
  WorkspaceEvent,
  WorkspaceSession,
  WorkspaceTask,
} from "./types";

export const recommendedTask: WorkspaceTask = {
  id: "phase-6-semantic-navigation",
  title: "Continue Semantic Navigation",
  description:
    "Connect indexed symbols to editor navigation while preserving the existing workspace intelligence boundary.",
  phase: "Phase 6 · IDE Intelligence",
  progress: 64,
  status: "recommended",
  relevantFiles: [
    "lib/intelligence/workspace-index-manager.ts",
    "lib/intelligence/symbols.ts",
    "components/FileViewer.tsx",
  ],
};

export const workspaceEvents: WorkspaceEvent[] = [
  {
    id: "event-1",
    kind: "verification.passed",
    title: "Verification passed",
    detail: "Runtime and task queue checks completed successfully.",
    actor: "Runtime",
    occurredAt: "2 min",
    tone: "success",
  },
  {
    id: "event-2",
    kind: "architecture.updated",
    title: "Architecture map updated",
    detail: "Three symbol relationships changed after the latest index.",
    actor: "Workspace",
    occurredAt: "6 min",
    tone: "neutral",
  },
  {
    id: "event-3",
    kind: "memory.updated",
    title: "Workspace memory refreshed",
    detail: "Phase 6 goals and the latest implementation checkpoint were restored.",
    actor: "Codier",
    occurredAt: "8 min",
    tone: "neutral",
  },
  {
    id: "event-4",
    kind: "documentation.updated",
    title: "Roadmap changed",
    detail: "IDE Intelligence is now the active development phase.",
    actor: "Git",
    occurredAt: "21 min",
    tone: "neutral",
  },
];

export const initialSession: WorkspaceSession = {
  id: "codexia-main-session",
  mode: "control-centre",
  status: "ready",
  selectedTask: recommendedTask,
  runtimeStatus: "paused",
  checkpoint: 3,
  briefing:
    "I restored the Phase 6 workspace and analysed the latest repository state. The runtime foundation is healthy. Semantic navigation is the strongest next step because the index and symbol model are already in place.",
  activeFile: "lib/intelligence/workspace-index-manager.ts",
  openFiles: [
    "lib/intelligence/workspace-index-manager.ts",
    "lib/agent/runtime/controller.ts",
  ],
  panel: "terminal",
  controlView: "home",
  ideTool: "explorer",
  expandedFolders: ["app", "components", "lib", "lib/agent", "lib/agent/runtime", "lib/intelligence", "docs", "docs/roadmap"],
  terminalHistory: [
    "alex@codexia % npm run verify",
    "runtime › validating task checkpoint 3",
    "✓ planner contracts  ✓ task queue  ✓ workspace index",
  ],
  bottomPanelOpen: true,
  codierPresence: {
    state: "analysing",
    message:
      "Workspace briefing ready. Three architectural changes were detected and the next mission is prepared.",
    priority: "attention",
    expression: "waving",
    relatedTaskId: recommendedTask.id,
    runtimeStatus: "paused",
    lastUpdatedAt: "Just now",
  },
  snapshot: {
    repository: "EchoInInk/codexia",
    branch: "main",
    phase: "Phase 6 · IDE Intelligence",
    health: 98,
    memoryStatus: "Loaded",
    graphStatus: "Updated 2 min ago",
    architectureScore: 94,
    indexedFiles: 298,
    symbolCount: 1842,
    activeWorkflows: 1,
    agentStatus: "Ready",
    gitStatus: "3 changes",
    verificationStatus: "Passing",
    recentChanges: 7,
  },
  events: workspaceEvents,
};

export const fileTree = [
  { depth: 0, name: "app", path: "app", parent: null, type: "folder" },
  { depth: 1, name: "api", path: "app/api", parent: "app", type: "folder" },
  { depth: 1, name: "page.tsx", path: "app/page.tsx", parent: "app", type: "file" },
  { depth: 0, name: "components", path: "components", parent: null, type: "folder" },
  { depth: 1, name: "FileViewer.tsx", path: "components/FileViewer.tsx", parent: "components", type: "file" },
  { depth: 1, name: "Sidebar.tsx", path: "components/Sidebar.tsx", parent: "components", type: "file" },
  { depth: 0, name: "lib", path: "lib", parent: null, type: "folder" },
  { depth: 1, name: "agent", path: "lib/agent", parent: "lib", type: "folder" },
  { depth: 2, name: "runtime", path: "lib/agent/runtime", parent: "lib/agent", type: "folder" },
  { depth: 3, name: "controller.ts", path: "lib/agent/runtime/controller.ts", parent: "lib/agent/runtime", type: "file" },
  { depth: 2, name: "task-queue", path: "lib/agent/task-queue", parent: "lib/agent", type: "folder" },
  { depth: 1, name: "intelligence", path: "lib/intelligence", parent: "lib", type: "folder" },
  { depth: 2, name: "workspace-index-manager.ts", path: "lib/intelligence/workspace-index-manager.ts", parent: "lib/intelligence", type: "file" },
  { depth: 2, name: "symbols.ts", path: "lib/intelligence/symbols.ts", parent: "lib/intelligence", type: "file" },
  { depth: 0, name: "docs", path: "docs", parent: null, type: "folder" },
  { depth: 1, name: "roadmap", path: "docs/roadmap", parent: "docs", type: "folder" },
  { depth: 2, name: "phases.md", path: "docs/roadmap/phases.md", parent: "docs/roadmap", type: "file" },
] as const;

export const editorLines = [
  "export class WorkspaceIndexManager {",
  "  private readonly eventSystem: AgentEventSystem;",
  "  private readonly storage: WorkspaceStorage;",
  "",
  "  async refresh(options: RefreshOptions): Promise<IndexDiff> {",
  "    const fingerprint = await this.createFingerprint();",
  "    const previous = await this.storage.loadFingerprint();",
  "",
  "    if (fingerprint.equals(previous)) {",
  "      return IndexDiff.unchanged();",
  "    }",
  "",
  "    const changedFiles = fingerprint.diff(previous);",
  "    const result = await this.incrementalIndex.update(changedFiles);",
  "",
  "    this.eventSystem.emit({",
  '      type: "workspace.indexed",',
  "      payload: result.summary,",
  "    });",
  "",
  "    return result;",
  "  }",
  "}",
];

export const editorContent: Record<string, string[]> = {
  "lib/intelligence/workspace-index-manager.ts": editorLines,
  "lib/agent/runtime/controller.ts": [
    "export class RuntimeController {",
    "  async resume(checkpoint: RuntimeCheckpoint) {",
    "    this.events.emit({ type: \"runtime.started\", checkpoint });",
    "    return this.workflow.continue(checkpoint);",
    "  }",
    "}",
  ],
  "app/page.tsx": [
    "export default function Home() {",
    "  return <UnifiedCodexiaShell />;",
    "}",
  ],
  "components/FileViewer.tsx": [
    "export function FileViewer({ file }: FileViewerProps) {",
    "  return <EditorDocument path={file.path} content={file.content} />;",
    "}",
  ],
  "components/Sidebar.tsx": [
    "export function Sidebar({ activeTool, onToolChange }: SidebarProps) {",
    "  return <WorkspaceNavigation active={activeTool} onChange={onToolChange} />;",
    "}",
  ],
  "lib/intelligence/symbols.ts": [
    "export interface IndexedSymbol {",
    "  name: string;",
    "  file: string;",
    "  range: SourceRange;",
    "}",
  ],
  "docs/roadmap/phases.md": [
    "# Phase 6 — IDE Intelligence",
    "",
    "- Semantic navigation",
    "- Symbol search",
    "- AI diagnostics",
    "- Architecture analysis",
  ],
};
